In [23]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
engin = create_engine("mysql+pymysql://root:123456@127.0.0.1:3306/test?charset=utf8mb4")
data = pd.read_sql("meal_order_detail1", con=engin)
# pivot_table方法可以实现透视表,aggfunc用于接收函数,index表示按什么进行分组
# pd.pivot_table(data[["order_id", "counts", "amounts"]], index="order_id", aggfunc=np.sum)
# index中的内容的顺序直接决定了排序的顺序，这里如果将order_id写在dishes_name后面就会先按照order_id进行分组
"""pd.pivot_table(data[["order_id", "counts", "amounts", "dishes_name"]], index=["order_id", "dishes_name"], 
aggfunc=np.sum)"""
# index表示行名称，columns表示列名称，margins表示求和，会出现一个名为ALL的行
pd.pivot_table(data[["order_id", "counts", "amounts", "dishes_name"]], index="order_id", 
               columns="dishes_name", margins=True, aggfunc=np.sum)

E:\pycharm\anaconda\installFile\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 518")
  result = self._query(query)

            amounts                                                        \
dishes_name  42度海之蓝  北冰洋汽水  38度剑南春  50度古井贡酒 52度泸州老窖   53度茅台  一品香酥藕   三丝鳝鱼
order_id
1002            NaN     NaN     NaN     NaN      NaN    NaN    NaN    NaN
1003            NaN     NaN     NaN     NaN      NaN    NaN    NaN    NaN
1004            NaN     NaN     NaN     NaN      NaN    NaN    NaN    NaN
1008            NaN     NaN     NaN     NaN      NaN    NaN    NaN    NaN
1011           99.0     NaN     NaN     NaN      NaN    NaN    NaN    NaN
...             ...     ...     ...     ...      ...    ...    ...    ...
894             NaN     NaN     NaN     NaN      NaN    NaN    NaN    NaN
905             NaN     NaN     NaN     NaN      NaN    NaN    NaN    NaN
906             NaN     NaN     NaN     NaN      NaN    NaN    NaN    NaN
909             NaN     NaN     NaN     NaN      NaN    NaN    NaN    NaN
All           297.0   115.0   480.0   450.0   1272.0  640.0  110.0  110.0

                                ... counts                             \
dishes_name 三色凉拌手撕兔 不加一滴油的酸奶蛋糕  ... 香酥两吃大虾 鱼香肉丝拌面  鲜美鳝鱼 鸡蛋、肉末肠粉 麻辣小龙虾
order_id                        ...
1002            NaN        NaN  ...    NaN    NaN   NaN     NaN   NaN
1003            NaN        NaN  ...    NaN    NaN   NaN     NaN   NaN
1004            NaN        NaN  ...    NaN    NaN   NaN     NaN   2.0
1008            NaN        NaN  ...    NaN    NaN   NaN     NaN   NaN
1011            NaN        NaN  ...    1.0    NaN   NaN     NaN   NaN
...             ...        ...  ...    ...    ...   ...     ...   ...
894             NaN        NaN  ...    NaN    NaN   NaN     NaN   NaN
905             NaN        NaN  ...    NaN    NaN   NaN     NaN   NaN
906             NaN        NaN  ...    NaN    NaN   NaN     NaN   NaN
909             NaN        NaN  ...    NaN    NaN   NaN     NaN   NaN
All           396.0       49.0  ...   38.0   12.0  10.0     3.0  66.0


dishes_name 黄尾袋鼠西拉子红葡萄酒 黄油曲奇饼干 黄花菜炒木耳 黑米恋上葡萄     All
order_id
1002                NaN    NaN    NaN    NaN     7.0
1003                NaN    NaN    NaN    NaN    10.0
1004                NaN    NaN    1.0    NaN    17.0
1008                NaN    NaN    NaN    NaN     5.0
1011                NaN    NaN    NaN    NaN    10.0
...                 ...    ...    ...    ...     ...
894                 NaN    NaN    NaN    NaN     5.0
905                 NaN    NaN    NaN    NaN     9.0
906                 NaN    NaN    NaN    NaN     9.0
909                 NaN    NaN    NaN    NaN     4.0
All                16.0    5.0   15.0   18.0  3088.0

[279 rows x 292 columns]

In [29]:
# 交叉表的创建，主要计算分组频率,values表示要求和的属性,fillna(0)可以将NaN强制转化为0
pd.crosstab(index=data["order_id"], columns=data["dishes_name"], values=data["counts"], margins=True, 
            aggfunc=np.sum).fillna(0)

dishes_name,42度海之蓝,北冰洋汽水,38度剑南春,50度古井贡酒,52度泸州老窖,53度茅台,一品香酥藕,三丝鳝鱼,三色凉拌手撕兔,不加一滴油的酸奶蛋糕,...,香酥两吃大虾,鱼香肉丝拌面,鲜美鳝鱼,鸡蛋、肉末肠粉,麻辣小龙虾,黄尾袋鼠西拉子红葡萄酒,黄油曲奇饼干,黄花菜炒木耳,黑米恋上葡萄,All
order_id,,,,,,,,,,,,,,,,,,,,,
1002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
1003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
1004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,17.0
1008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
1011,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
905,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
906,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
909,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
All,5.0,45.0,6.0,5.0,8.0,5.0,11.0,2.0,6.0,7.0,...,38.0,12.0,10.0,3.0,66.0,16.0,5.0,15.0,18.0,3088.0