In [44]:
import requests,pandas
url = "https://api.inews.qq.com/newsqa/v1/query/inner/publish/modules/list?modules=chinaDayList,chinaDayAddList,cityStatis,nowConfirmStatis,provinceCompare"
url_list = requests.get(url).json()["data"]["chinaDayAddList"]  
data_list = ["date", "confirm", "suspect", "dead", "heal", "importedCase", "deadRate", "healRate"]
for i in data_list:
    locals()[i] = []
for i in url_list:
    for j in data_list:
        locals()[j].append(i[j])
china_data = pandas.DataFrame({"日期": date, "新增确诊": confirm, "疑似病例": suspect,"新增死亡": dead,"新增治愈": heal,
                               "境外输入": importedCase,"死亡率": deadRate, "治愈率": healRate})
china_data.to_csv("./china_data.csv", index=False)

In [45]:
china_data

        日期  新增确诊  疑似病例  新增死亡  新增治愈  境外输入  死亡率    治愈率
0    01.20    77    27     0     0     0  0.0    0.0
1    01.21   149    53     3     0     0  2.0    0.0
2    01.22   131   257     8     0     0  6.1    0.0
3    01.23   259   680     8     6     0  3.1    2.3
4    01.24   444  1118    16     3     0  3.6    0.7
..     ...   ...   ...   ...   ...   ...  ...    ...
203  08.10   113     2     3   122    31  2.7  108.0
204  08.11    61     1     3   195    16  4.9  319.7
205  08.12    82     1     5   200    11  6.1  243.9
206  08.13    99     2     3   170    22  3.0  171.7
207  08.14    70     1     1   154    14  1.4  220.0

[208 rows x 8 columns]