In [60]:
# 招聘数据探索分析
import pandas as pd
import re
job_info = pd.read_csv("./tmp/job_info.csv", encoding="gbk")
job_info.columns = ["公司","岗位","工作地点","工资","发布日期"]
# job_info = job_info.rename(columns={"字节跳动":"公司","数据产品经理":"岗位","北京":"工作地点","2-3.5万/月":"工资",
#                     "09-03":"发布日期"})
job_info["岗位"].value_counts().idxmax()  # idxmax()可以寻找最大值的索引
# job_info.loc[job_info["发布日期"]=="09-03", :]
job_info[job_info["发布日期"]=="09-03"]
a = job_info["工作地点"].agg(lambda x : "深圳" in x)  # 返回值是bool类型
b = job_info["岗位"]=="数据分析师"  # 返回值为bool类型
job_info[a & b]  # 取ab都为bool类型的值
def get_number(string=None):
    try:
        if string[-3] == "万":
            c = [float(i) * 10000 for i in re.findall("\d+\.*\d*", string)]
        elif string[-3] == "千":
            c = [float(i) * 1000 for i in re.findall("\d+\.*\d*", string)]
        if string[-1] == "年":
            c = [i/12 for i in c]
        return c
    except:
        return None
mid = job_info["工资"].agg(get_number)
job_info["最低工资"] = mid.str[0]
job_info["最高工资"] = mid.str[1]
job_info

,公司,岗位,工作地点,工资,发布日期,最低工资,最高工资
0,甲骨文（中国）软件系统有限公司,数据产品经理,长沙,NaN,09-03,NaN,NaN
1,莱茵技术(上海)有限公司 TUV Rhei...,数据产品经理,上海-静安区,NaN,09-03,NaN,NaN
2,百度在线网络技术（北京）有限公司...,数据产品经理,北京,2-4万/月,09-03,20000.0,40000.0
3,携程旅行网业务区,数据产品经理,上海-长宁区,1.5-2万/月,09-03,15000.0,20000.0
4,嘉吉投资（中国）有限公司南京分公...,数据产品经理,南京,NaN,09-03,NaN,NaN
...,...,...,...,...,...,...,...
5494,深圳市创荣发电子有限公司,仓库数据分析员,深圳,2-2.5万/月,09-04,20000.0,25000.0
5495,深圳市宝华诚投资管理有限公司,仓库数据分析员,深圳-龙华新区,6-8千/月,09-04,6000.0,8000.0
5496,广州市卡思投资有限公司,仓库数据分析员,深圳-福田区,0.8-1万/月,09-04,8000.0,10000.0
5497,深圳市迪比科电子科技有限公司,仓库数据分析员,深圳-龙华新区,1.5-2.5万/月,09-04,15000.0,25000.0
5498,武汉锦瑞技术有限公司,仓库数据分析员,武汉-蔡甸区,3-4.5千/月,09-04,3000.0,4500.0